"""add reviewss

Revision ID: 3697afaed553
Revises: 297b48f44b27
Create Date: 2024-04-04 14:03:56.773946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3697afaed553'
down_revision = '297b48f44b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('item_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_reviews_column_id_items', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_item_id_items'), 'reviews', 'items', ['item_id'], ['id'])
    op.drop_column('reviews', 'column_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('column_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_reviews_item_id_items'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_column_id_items', 'reviews', 'items', ['column_id'], ['id'])
    op.drop_column('reviews', 'item_id')
    # ### end Alembic commands ###
